// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVgTkBp93CKCKzy0die-UAyjFkt7Vxuzk',
    appId: '1:293871012883:web:da0c215274199975ae43e6',
    messagingSenderId: '293871012883',
    projectId: 'sbox-d04a7',
    authDomain: 'sbox-d04a7.firebaseapp.com',
    databaseURL: 'https://sbox-d04a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sbox-d04a7.firebasestorage.app',
    measurementId: 'G-CJF75T16MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaK9rwX3bD49BPIFApc8Rt_pTtVuCuco8',
    appId: '1:293871012883:android:6966bfef252c5c82ae43e6',
    messagingSenderId: '293871012883',
    projectId: 'sbox-d04a7',
    databaseURL: 'https://sbox-d04a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sbox-d04a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOkFZTDurIBkhqnUl0HnmiiF38rr3hbco',
    appId: '1:293871012883:ios:97bb48e347f2f0cbae43e6',
    messagingSenderId: '293871012883',
    projectId: 'sbox-d04a7',
    databaseURL: 'https://sbox-d04a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sbox-d04a7.firebasestorage.app',
    iosBundleId: 'com.example.realFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOkFZTDurIBkhqnUl0HnmiiF38rr3hbco',
    appId: '1:293871012883:ios:97bb48e347f2f0cbae43e6',
    messagingSenderId: '293871012883',
    projectId: 'sbox-d04a7',
    databaseURL: 'https://sbox-d04a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sbox-d04a7.firebasestorage.app',
    iosBundleId: 'com.example.realFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVgTkBp93CKCKzy0die-UAyjFkt7Vxuzk',
    appId: '1:293871012883:web:983e4426ec33ab13ae43e6',
    messagingSenderId: '293871012883',
    projectId: 'sbox-d04a7',
    authDomain: 'sbox-d04a7.firebaseapp.com',
    databaseURL: 'https://sbox-d04a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sbox-d04a7.firebasestorage.app',
    measurementId: 'G-L9NY9XDEB3',
  );
}
